### ISSUE TITLE
Does this work???

### ISSUE THREAD

**Issue by ismohamedi** [nishantonline1/DjangoWhatsAppBot#1]

**Comment by nishantonline1** [comment]
Yes, This is code from my own running app

**Comment by ismohamedi** [comment]
How can that be possible without Django setting, manage.py, how do you
start server on that??

Ismaili Mohamedi
founder of CodeTechDevelopers community,
Software Developer,
mobile : 0763080423

**Comment by nishantonline1** [comment]
This is just a sample code for django API, not the whole django setup.  Copy paste the codes in views.py file in your django app. If you want any further help then feel free to ask.

**Comment by ismohamedi** [comment]
Okay I get you there, I was confused with that Django code structure to be run with single file, okay fine no problem
